### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by saltsoftdrink** [elastic-rock/Candle#7] opened 2024-02-19 19:09 UTC
If we turn on random colors it doesn't get turn off

**Comment by elastic-rock** [comment] 2024-02-19 19:25
Could you please make a screen recording and upload it here? Thank you.

**Comment by bojidar-bg** [comment] 2024-03-08 16:05
Can confirm. Here's a recording of me fighting with the birthday candle button; after I turn it on, no amount of pressing buttons ever stops the rotation of orange hue other than quitting the app altogether.

![gif-20240308-180229](https://github.com/elastic-rock/Candle/assets/5276727/a9acca12-4ea6-4ead-b70a-4420fa4645a4)

Thanks for making this, BTW! Was looking for a quick floodlight for a project, and this is coming in clutch :blush: :green_heart:

**Comment by bojidar-bg** [comment] 2024-03-08 16:11
Ooh.. looking at the code, I can see you call stopCandleEffect when the Settings button is pressed, and indeed that one works! XD The issue here seems to be that once the animation starts, the scaffold remains open, and thus we don't even see that there is a "Stop" button behind it. :sweat_smile: You probably want to contract the scaffold around startCandleEffect (`scope.launch { scaffoldState.bottomSheetState.collapse() }`?), or add stopCandleEffect calls for each of the buttons and the two color sliders when moved manually. (:

**Comment by elastic-rock** [comment] 2024-03-08 20:26
Thank you @bojidar-bg for clarifying the issue. The issue is now fixed by making the bottom sheet collapse once the candle effect starts.

**Closed by elastic-rock** 2024-03-08 20:26 UTC
