### ISSUE TITLE
Max brightness when slider is on the left

### ISSUE THREAD

**Issue by salihmarangoz** [elastic-rock/Candle#3] opened 2023-10-28 00:15 UTC
Brightness of my phone's screen goes maximum with the slider's minimum value. 

model: xiaomi mi a1

**Comment by elastic-rock** [comment] 2023-10-28 13:07
Does the brightness change at all when the slider is moved?

**Comment by salihmarangoz** [comment] 2023-10-28 13:19
yes, it changes. 

correction: it doesn't maximize the brightness but increases suddenly (to a mid-level brightness) when the slider value is minimized (on the leftmost side)

**Comment by elastic-rock** [comment] 2023-10-28 13:21
Could you film the device?
-------- Original Message --------

**Comment by salihmarangoz** [comment] 2023-10-29 01:48
https://github.com/elastic-rock/Candle/assets/12991962/ed94170c-285b-43bf-a71b-5d055bdd6b23

**Comment by elastic-rock** [comment] 2023-11-04 17:05
What is your device model? Do you have a custom rom installed?

**Comment by elastic-rock** [comment] 2023-11-04 17:26
The thing is, it seems to me that this is a device issue and not necessarily of the app (whilst I could programmatically counter for it). It seems that your device takes the [screenTimeout](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#screenBrightness) value of 0.0 as not overriding. However, the value of [0.0 should be taken as minimum](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#BRIGHTNESS_OVERRIDE_OFF) and [-1.0 as not overriding](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#BRIGHTNESS_OVERRIDE_NONE). I would prefer that the issue is fixed with the OS developers (if possible) rather than in the app, as other people would then not be able to achieve the actual minimum or there would have to be a field somewhere in the app to set the minimum value.

**Comment by salihmarangoz** [comment] 2023-11-04 21:58
You are right. It is just a stupid bug... (also here: https://gitlab.com/LineageOS/issues/android/-/issues/5021)

So the bug is out there and since it is not a significant bug probably it will not be fixed by the developers. I think it would be best to check if the minimum value is equal to zero, and then add a small value to workaround this bug.

**Comment by elastic-rock** [comment] 2023-11-05 11:09
Apps cannot check the maximum and minimum values of the device and it would therefore require that the minimum value of the slider would be set higher for all users. I am sorry to say, but I consider that to be an issue of the LineageOS port and therefore out of the scope of this project.

**Closed by elastic-rock** 2023-11-05 11:09 UTC
Labels: bug
